api/app.py
import settings
from flask import Flask
from views import router

app = Flask(__name__,
static_folder='static',
static_url_path='')
app.config["UPLOAD_FOLDER"] = settings.UPLOAD_FOLDER
app.secret_key = "secret key"
app.register_blueprint(router)

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=settings.API_DEBUG)

api/views.py
import os
import settings
import utils as utils
import json
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from middleware import model_predict


router = Blueprint("app_router", __name__, template_folder="templates")


@router.route("/", methods=["GET", "POST"])
def index():
    """
    GET: Index endpoint, renders our HTML code.

    POST: Used in our frontend so we can upload and show an image.
    When it receives an image from the UI, it also calls our ML model to
    get and display the predictions.
    """
    if request.method == "GET":
        return render_template("index2.html")

    if request.method == "POST":
        # File received but no filename is provided, show basic UI
        file = request.files["file"]
        name = request.form.get("name")
        description = request.form.get("description")

        # if file.filename == "":
        #     flash("No image selected for uploading")
        #     return redirect(request.url)
        #       
        if utils.allowed_name(name) == False:
            flash("No valid text for product title. Min. extension 10 characters.")
            return redirect(request.url)

        if utils.allowed_description(description) == False:
            flash("No valid text for product description. Min. extension 20, max. 400")
            return redirect(request.url)
        
        if utils.allowed_description(description) and utils.allowed_name(name):
        # THREE VALID INPUTS
            if file and utils.allowed_file(file.filename):
            # In order to correctly display the image in the UI and get model
            # predictions you should implement the following:
            #   1. Get an unique file name using utils.get_file_hash() function
            #   2. Store the image to disk using the new name
            #   3. Send the file to be processed by the `model` service
            #      Hint: Use middleware.model_predict() for sending jobs to model
            #            service using Redis.
            #   4. Update `context` dict with the corresponding values
            # TODO
                filename = utils.get_file_hash(file)
                # Delete previous images 
                for f in os.listdir(settings.UPLOAD_FOLDER):
                    os.remove(os.path.join(settings.UPLOAD_FOLDER, f))
                file.save(os.path.join(settings.UPLOAD_FOLDER, filename))
                prediction = model_predict(name, description, filename)
                context = {"prediction": prediction,
                           "filename": filename
                          }
                return render_template("index2.html", filename=filename, context=context, name=name, description=description)
        # File received and but it isn't an image
            else:
                filename = "no_image"
                prediction = model_predict(name, description, filename)
                context = {"prediction": prediction,
                           "filename": filename
                          }
                return render_template("index2.html", filename=filename, context=context, name=name, description=description)            

@router.route("/display/<filename>")
def display_image(filename):
    """
    Display uploaded image in our UI.
    """
    if filename != "no_image":
       return redirect(url_for("static", filename="uploads/" + filename), code=301)
    else:
        return redirect(url_for("static", filename="images/no_image.jpg"), code=301)


@router.route("/predict", methods=["POST"])
def predict():
    """
    Endpoint used to get predictions without need to access the UI.

    Parameters
    ----------
    file : str
        Input image we want to get predictions from.

    name : str
        Input name text we want to get predictions from.

    description: str
        Input description text we want to get predictions from.

    Returns
    -------
    flask.Response
        JSON response from our API having the following format:
            {
                "success": bool,
                "prediction": str,
                "score": float,
            }

        - "success" will be True if the input file is valid and we get a
          prediction from our ML model.
        - "prediction" model predicted class as string.
        - "score" model confidence score for the predicted class as float.
    """
    # To correctly implement this endpoint you should:
    #   1. Check a file was sent and that file is an image
    #   2. Store the image to disk
    #   3. Send the file to be processed by the `model` service
    #      Hint: Use middleware.model_predict() for sending jobs to model
    #            service using Redis.
    #   4. Update and return `rpse` dict with the corresponding values
    # If user sends an invalid request (e.g. no file provided) this endpoint
    # should return `rpse` dict with default values HTTP 400 Bad Request code
    # TODO
    rpse = {"success": False, "prediction": None, "score": None}
    
    name = request.form.get("name")
    description = request.form.get("description")
    file = request.files["file"]

    if utils.allowed_description(description) and utils.allowed_name(name):

        if "file" in request.files and utils.allowed_file(file.filename):
            file.save(os.path.join(settings.UPLOAD_FOLDER, file.filename))
            rpse['prediction'] = model_predict(name, description, file.filename)
            rpse['success'] = True
        else:
            image_name = "no_image"    
            rpse['prediction'] = model_predict(name, description, image_name)
            rpse['success'] = True
            return jsonify(rpse)
    else:
        return jsonify(rpse), 400     


@router.route("/feedback", methods=["GET", "POST"])
def feedback():
    """
    Store feedback from users about wrong predictions on a plain text file.

    Parameters
    ----------
    report : request.form
        Feedback given by the user with the following JSON format:
            {
                "filename": str,
                "name": str,
                "description": str,
                "prediction": str,
                "score": float
            }

        - "filename" corresponds to the image used stored in the uploads
          folder.
        - "prediction" is the model predicted class as string reported as
          incorrect.
        - "score" model confidence score for the predicted class as float.
    """
    context = {"feedback" : request.form.get("feedback")}
    prediction_raw = request.form.get("report")
    prediction = json.loads(prediction_raw.replace("\'", "\""))
    return render_template("feedback.html", context=context, prediction=prediction)
    #report = request.form.get("report")
    # Store the reported data to a file on the corresponding path
    # already provided in settings.py module
   

   

api/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
    <title>E-commerce category predictor</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="css/spinner.css">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets --> 
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <style>
        /* Center the loader */
        /* #loader {
          position: absolute;
          left: 50%;
          top: 50%;
          z-index: 1;
          width: 120px;
          height: 120px;
          margin: -76px 0 0 -76px;
          border: 16px solid #f3f3f3;
          border-radius: 50%;
          border-top: 16px solid #3498db;
          -webkit-animation: spin 2s linear infinite;
          animation: spin 2s linear infinite;
        }
        
        @-webkit-keyframes spin {
          0% { -webkit-transform: rotate(0deg); }
          100% { -webkit-transform: rotate(360deg); }
        }
        
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
        */
        /* Add animation to "page content" */
        /*
        .animate-bottom {
          position: relative;
          -webkit-animation-name: animatebottom;
          -webkit-animation-duration: 1s;
          animation-name: animatebottom;
          animation-duration: 1s
        }
        
        @-webkit-keyframes animatebottom {
          from { bottom:-100px; opacity:0 } 
          to { bottom:0px; opacity:1 }
        }
        
        @keyframes animatebottom { 
          from{ bottom:-100px; opacity:0 } 
          to{ bottom:0; opacity:1 }
        } */
        
        #myDiv {
          display: none;
          text-align: center;
        }
        </style>
    </head>
    <body class="main-layout" onload="myFunction()">
	<!-- header section start -->
	<div class="header_section header_main">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="logo"><a href="#"><img src="images/top-k-price.png"></a></div>
				</div>
				<div class="col-sm-9">
					<nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                           <a class="nav-item nav-link" href="#">Home</a>
                           <a class="nav-item nav-link" href="#">Categories</a>
                           <a class="nav-item nav-link" href="#">Offers</a>
                           <a class="nav-item nav-link" href="#">Supermarket</a>
                           <a class="nav-item nav-link" href="#">Sell</a>
                           <a class="nav-item nav-link last" href="#"><img src="images/search_icon.png"></a>
                           <a class="nav-item nav-link last" href="#"><img src="images/shop_icon.png"></a>
                        </div>
                    </div>
                    </nav>
				</div>
			</div>
		</div>
	</div>
        {% if context['feedback'] %}
        
        <div class="collection_text" id="uploading">Your product is uploading ... </div>
        <div class="collection_text" id="uploaded" style="display:none;">Your product was successfully uploaded</div>
        
        <div class="container" style="min-height:80px;">
                <!-- <div id="loader" ></div> -->
                <div class="collection_section"></div>
                <div id="loader" style="text-align:center;"><img src="/images/ezgif-2-6d0b072c3d3f.gif"></div>
                <div style="display:none;" id="myDiv" class="animate-bottom">
                <div id="uploader" style="text-align:center;display:none;"><img src="/images/tick-icon.png", width="30%""></div>
                <div style="display:none;" id="myDiv" class="animate-bottom">
                 
                </div> 
            </div>
            </div>
        </div>
        {% endif %}
        
        </div>
        <!-- new collection section end -->
        <!-- section footer start -->
        <div class="section_footer">
            <div class="container">
                <div class="mail_section">
                    <div class="row">
                        <div class="col-sm-6 col-lg-2">
                            <div><a href="#"><img src="images/top-k-price-footer.png"></a></div>
                        </div>
                        <div class="col-sm-6 col-lg-2">
                            <div class="footer-logo"><img src="images/phone-icon.png"><span class="map_text">(71) 1234567890</span></div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="footer-logo"><img src="images/email-icon.png"><span class="map_text">demo@anyoneai.com</span></div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="social_icon">
                                <ul>
                                    <li><a href="#"><img src="images/fb-icon.png"></a></li>
                                    <li><a href="#"><img src="images/twitter-icon.png"></a></li>
                                    <li><a href="#"><img src="images/in-icon.png"></a></li>
                                    <li><a href="#"><img src="images/google-icon.png"></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-2"></div>
                    </div>
                </div> 
                <div class="footer_section_2">
                    <div class="row">
                        <div class="col-sm-4 col-lg-2">
                            <p class="dummy_text"> ipsum dolor sit amet, consectetur ipsum dolor sit amet, consectetur  ipsum dolor sit amet,</p>
                        </div>
                        <div class="col-sm-4 col-lg-2">
                            <h2 class="shop_text">Address </h2>
                            <div class="image-icon"><img src="images/map-icon.png"><span class="pet_text">No 40 Baria Sreet 15/2 NewYork City, NY, United States.</span></div>
                        </div>
                        <div class="col-sm-4 col-md-6 col-lg-3">
                            <h2 class="shop_text">Our Company </h2>
                            <div class="delivery_text">
                                <ul>
                                    <li>Delivery</li>
                                    <li>Legal Notice</li>
                                    <li>About us</li>
                                    <li>Secure payment</li>
                                    <li>Contact us</li>
                                </ul>
                            </div>
                        </div>
                    <div class="col-sm-6 col-lg-3">
                        <h2 class="adderess_text">Products</h2>
                        <div class="delivery_text">
                                <ul>
                                    <li>Prices drop</li>
                                    <li>New products</li>
                                    <li>Best sales</li>
                                    <li>Contact us</li>
                                    <li>Sitemap</li>
                                </ul>
                            </div>
                    </div>
                    <div class="col-sm-6 col-lg-2">
                        <h2 class="adderess_text">Newsletter</h2>
                        <div class="form-group">
                            <input type="text" class="enter_email" placeholder="Enter Your email" name="Name">
                        </div>
                        <button class="subscribr_bt">Subscribe</button>
                    </div>
                    </div>
                    </div> 
                </div>
            </div>
        </div>
        <!-- section footer end -->
        <div class="copyright">2022 All Rights Reserved.<a href="#"> E-commerce predictor</a></div>
        <script>
        var myVar;
        
        function myFunction() {
          myVar = setTimeout(showPage, 5000);
        }
        
        function showPage() {
          document.getElementById("loader").style.display = "none";
          document.getElementById("uploading").style.display = "none";
          document.getElementById("myDiv").style.display = "block";
          document.getElementById("uploaded").style.display = "block";
          document.getElementById("uploader").style.display = "block";
        }
        </script>
    </body>
</html>

api/templates/index.html
<!doctype html>
<html>
    <head>
        <title>E-commerce category predictor</title>
    </head>
    <body>
        <h2>Hello! What are you selling today?</h2>
        <p>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
        </p>
        {% if filename %}
            <div>
                <img src="{{ url_for('app_router.display_image', filename=filename) }}">
            </div>
            {% if context['prediction'] %}
                <div class="row">
                    <div class="col-25">
                    <label for="subject">Predicted class: {{ context['prediction'] }} </label><br>
                    </div>
                </div>
                <form id="form" method="POST" action="/feedback">
                    <button type="submit">Report incorrect answer</button><br>
                    <input name="report" style="visibility: hidden;" value="{'filename': '{{ filename }}', 'prediction': '{{ context['prediction'] }}', 'score': {{ context['score'] }} }"/>
                </form>
            {% endif %}
        {% endif %}
        <form method="post" action="/" enctype="multipart/form-data">
            <label for="name">Choose a title for the ad</label><br>
            <input type="text" name="name" required><br><br>
            <label for="description">Write a short description:</label><br>
            <input type="text" name="description" required><br><br>
            <label for="file">Upload an image of your product</label><br>
            <input type="file" name="file" autocomplete="off" required><br><br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>